---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
library(tidyverse)
library(viridis)
## Loading required package: viridisLite
library(p8105.datasets)

library(plotly)
library(shiny)
```


```{r}
## data manipulation


data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  rename(latitude = lat, longitude = long) %>%
  select(
    boro = neighbourhood_group, neighbourhood, rating, price, room_type,
    latitude, longitude) %>%
  filter(!is.na(rating))


## Create an input widget
boros = nyc_airbnb %>% distinct(boro) %>% pull()

# selectInput widget
selectInput(
  "boro_choice", ## naming the input chunk
  label = h3("Select boro"), 
  choices = boros, selected = "Manhattan")## default option

## set the range
max_price = 1000
min_price = nyc_airbnb %>% distinct(price) %>% min()
  
# sliderInput widget
sliderInput(
  "price_range", 
  label = h3("Choose price range"), 
  min = min_price, max = max_price, value = c(100, 400))

## radiobuttons
room_choice = nyc_airbnb %>% distinct(room_type) %>% pull()

# radioButtons widget
radioButtons(
  "room_choice", 
  label = h3("Choose room type"),
  choices = room_choice, selected = "Entire home/apt")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

renderPlotly({ 
  nyc_airbnb %>%
        filter(
            boro == input[["boro_choice"]],
            price %in% input$price_range[1]:input$price_range[2],
            room_type == input$room_choice
            ) %>% 
        mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
        plot_ly(
            x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
            alpha = 0.5, color = ~price, text = ~text_label)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint(
    ## change the "list" of input
    input[["price_range"]]
)
```

### Chart C

```{r}
renderPrint(
    ## change the "list" of input
    input[["room_choice"]]
)
```

